spring:
  application:
    name: shop-service

server:
  port: 8100

eureka-server:
  host: localhost
  port: 8761
  postfix: default

redis:
  host: localhost
  port: 6379

eureka:
  user:
    name: admin
    password: 1234

  client:
    # disable while no profile
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.user.name}:${eureka.user.password}@${eureka-server.host}:${eureka-server.port}/eureka

55g:
  resource:
    path: /static
  log:
    path: .
---
# on profile 'live'
spring:
  config:
    activate:
      on-profile: live

  datasource:
    url: jdbc:mysql://133.186.241.167:3306/project_be7_55g.com_prod
    username: be7_55g
    password: eY3WQW!(yOBcB@SV
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

redis:
  postfix: live

eureka:
  client:
    enabled: true

eureka-server:
  postfix: live

logging:
  file:
    name: ${55g.log.path}/shop-live.log
  logback:
    rollingpolicy:
      max-history: 100
      file-name-pattern: ${55g.log.path}/shop-live-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100KB
  level:
    root: info
    shop.S5G.shop: info
55g:
  log:
    path: /logs/live/shop

---
# on profile 'dev'
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/project_be7_55g.com_dev
    username: be7_55g
    password: eY3WQW!(yOBcB@SV
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

redis:
  postfix: dev

eureka:
  client:
    enabled: true

eureka-server:
  port: 8762
  postfix: dev

server:
  port: 8200
logging:
  file:
    name: ${55g.log.path}/shop-dev.log
  logback:
    rollingpolicy:
      max-history: 100
      file-name-pattern: ${55g.log.path}/shop-dev-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100KB
  level:
    root: debug
    shop.S5G.shop: trace

55g:
  log:
    path: /logs/dev/shop
---
# on profile 'docker'
spring:
  config:
    activate:
      on-profile: docker

eureka-server:
  host: 55g-eureka

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.user.name}:${eureka.user.password}@${eureka-server.host}-${eureka-server.postfix}:${eureka-server.port}/eureka

redis:
  host: redis-${redis.postfix}
  port: 6379

---
spring:
  config:
    activate:
      on-profile: embed-db

  jpa:
    database: h2
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: true
        use_sql_comments: true
        highlight_sql: true


logging:
  level:
    shop.S5G: trace
    root: info

