spring:
  application:
    name: shop-service

server:
  port: 8100

eureka-server:
  host: localhost
  port: 8761
  postfix: default

eureka:
  client:
    # disable while no profile
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka-server.host}:${eureka-server.port}/eureka

---
# on profile 'live'
spring:
  config:
    activate:
      on-profile: live

eureka:
  client:
    enabled: true

eureka-server:
  postfix: live

---
# on profile 'dev'
spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    enabled: true

eureka-server:
  port: 8762
  postfix: dev

server:
  port: 8200

---
# on profile 'docker'
spring:
  config:
    activate:
      on-profile: docker

eureka-server:
  host: 55g-eureka

eureka:
  client:
    service-url:
      defaultZone: http://${eureka-server.host}-${eureka-server.postfix}:${eureka-server.port}/eureka
