spring:
  application:
    name: shop-service

server:
  port: 8100

eureka-server:
  host: localhost
  port: 8761
  postfix: default

eureka:
  user:
    name: admin
    password: 1234

  client:
    # disable while no profile
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.user.name}:${eureka.user.password}@${eureka-server.host}:${eureka-server.port}/eureka

55g:
  resource:
    path: /static
  log:
    path: .
logging:
  file:
    name: ${55g.log.path}/shop.log
---
# on profile 'live'
spring:
  config:
    activate:
      on-profile: live

eureka:
  client:
    enabled: true

eureka-server:
  postfix: live

logging:
  file:
    name: ${55g.log.path}/shop-live.log
  logback:
    rollingpolicy:
      max-history: 100
      file-name-pattern: ${55g.log.path}/shop-live-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100KB
  level:
    root: info
    shop.S5G.shop: info
55g:
  log:
    path: /logs/live/shop
---
# on profile 'dev'
spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    enabled: true

eureka-server:
  port: 8762
  postfix: dev

server:
  port: 8200
logging:
  file:
    name: ${55g.log.path}/shop-dev.log
  logback:
    rollingpolicy:
      max-history: 100
      file-name-pattern: ${55g.log.path}/shop-dev-%d{yyyy-MM-dd}.%i.log
      max-file-size: 100KB
  level:
    root: debug
    shop.S5G.shop: trace

55g:
  log:
    path: /logs/dev/shop
---
# on profile 'docker'
spring:
  config:
    activate:
      on-profile: docker

eureka-server:
  host: 55g-eureka

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.user.name}:${eureka.user.password}@${eureka-server.host}-${eureka-server.postfix}:${eureka-server.port}/eureka