spring:
  profiles:
    active: default

  application:
    name: shop-service

  config:
    import: configserver:http://admin:55g.com7@localhost:9000

  cloud:
    config:
      label: main

---
spring:
  config:
    activate:
      on-profile: embed-db

  jpa:
    database: h2
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: true
        use_sql_comments: true
        highlight_sql: true


logging:
  level:
    shop.S5G: trace
    root: info
