spring:
  profiles:
    active: default

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/55g
    username: root
    password:

  application:
    name: shop-service

  config:
    import: optional:configserver:http://localhost:9000

  cloud:
    config:
      label: main

  rabbitmq:
    host: ${rabbitmq.host}
    port: 5672
    username: guest
    password: guest

server:
  port: 8000
rabbitmq:
  host: localhost

redis:
  host: localhost
  port: 6379

management:
  endpoints:
    web:
      exposure:
        include: refresh,busrefresh,health

payment:
  toss:
    secretkey: secret

---
spring:
  config:
    activate:
      on-profile: live

    import: optional:configserver:http://55g-config-live:9000

redis:
  postfix: live

---
# on profile 'dev'
spring:
  config:
    activate:
      on-profile: dev

    import: optional:configserver:http://55g-config-dev:9050

redis:
  postfix: dev

---
# on profile 'docker'
spring:
  config:
    activate:
      on-profile: docker

redis:
  host: redis-${redis.postfix}
  port: 6379

---
spring:
  config:
    activate:
      on-profile: embed-db




  jpa:
    database: h2
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        generate_statistics: true
        use_sql_comments: true
        highlight_sql: true
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full


logging:
  level:
    shop.s5g: trace
    root: info




