insert into Book(book_id,
                 publisher_id,
                 book_status_id,
                 title,
                 chapter,
                 descreption,
                 published_date,
                 isbn,
                 price,
                 discount_rate,
                 is_packed,
                 stock,
                 views,
                 created_at
)
values (1,
        11,
        111,
        '걸리버 여행기',
        '여행출발, 끝',
        '이 책은 전래동화이다.',
        '1990-10-10 10:50:00',
        '978-3-16-148410-0',
        20000,
        10.5,
        true,
        100,
        3000,
        '2000-10-10 10:50:00'
       );